server:
  protocol: http
  host: 127.0.0.1
  port: 7150
log:
  level: debug # off, trace, debug, info, warn, error
  format: pretty # compacy, full, json, pretty
  crates:
    - inventario_api # name of the project
    - axum
    - tower-http
    - tower
database:
  uri: postgresql://postgres:postgres@localhost:5432/dev_inventario
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: dev_inventario
  ssl: false
redis:
  uri: redis://localhost:6379
auth:
  access:
    # Path to the keys relative to Cargo.toml file.
    private_key: config/security/keys/access_key.pem
    public_key: config/security/keys/access_key_pub.pem
    exp: 900 # Seconds 15 minutes
  refresh:
    private_key: config/security/keys/refresh_key.pem
    public_key: config/security/keys/refresh_key_pub.pem
    exp: 2419200 # Seconds 4 Weeks
